var NavDate=[
				[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				]
			];
var CateDate=[
				[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				}
				],[
				{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				]
			];