var NavDate=[
				[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				],[
				{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/mix3-320.png",
				url:"javascript",
				tag:"新品",
				name:"小米-mix3",
				price:"3299"
				},{
				src:"images/note7320-220.png",
				url:"javascript",
				tag:"新品",
				name:"红米Note 7",
				price:"1299"
				}
				]
			];
var CateDate=[
				[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				}
				],[
				{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/note7320-220.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"红米note7"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				],[
				{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				},{	
					url:"javascript",
					src:"images/mi9se-320.png",
					name:"小米9se"
				}
				]
			];
var ElecDate=[
				[
					{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						src:"images/p1.jpg",
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						des:'小米净水器真的很棒，你可以用试试',
						now:'1799元',
						src1:"images/ca.png",
						name:'浏览更多',
						hot:'热门'
					}
				],[
					{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p1.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						des:'小米净水器真的很棒，你可以用试试',
						now:'1799元',
						src1:"images/ca.png",
						name:'浏览更多',
						hot:'热门'
					}
				],[
					{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						des:'小米净水器真的很棒，你可以用试试',
						now:'1799元',
						src1:"images/ca.png",
						name:'浏览更多',
						hot:'热门'
					}
				],[
					{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						url:'jsvascript:',
						src:"images/p2.jpg",
						des:'骁龙855，索尼4800万超广角微距三摄索尼4800万超广角微距三摄',
						now:'3699元',
						name:'小米9 6GB +128G',
						pre:'4699元',
						flag:'减 800 元',
						views:{
							commen:'电视收到了,虽然有点晚,我感觉还不错，你觉得呢？',
						author:'评论来自于kuazhu'
						}	
					},{
						des:'小米净水器真的很棒，你可以用试试',
						now:'1799元',
						src1:"images/ca.png",
						name:'浏览更多',
						hot:'热门'
					}
				]
			];
			