var aNavDate=[
			[
			{
				url:"#",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],
			[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],
			[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}],[
			{
				url:"#",
				tag:"新品",
				src:"../images/mi9-320.png",
				name:"小米九",
				price:2999
			},{
				url:"#",
				tag:"特卖",
				src:"../images/13.3huise.png",
				name:"小米九",
				price:3228
			}]
];
var aBanCont=[
		[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}
		],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}],[
		{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		},{
			url:'#',
			src:"../images/mi9-320.png",
			name:"小米九"
		}]
];
var aHouseCont=[
							
			[{
				src : "../images/手机.png" ,
				name:'小米9 6+128GB',
				des:"骁龙855，索尼4800万超广角微距三摄",
				price:{
					strong:"2999元",
					del:"5000y元"
					},
				lab:"新品"
			}			
			]
]

						